[build]
target = "aarch64-linux-android"

[target.aarch64-linux-android]
ar = "android-ndk/arm64/bin/aarch64-linux-android-clang"
linker = "android-ndk/arm64/bin/aarch64-linux-android-clang"
runner = "runners/adb_runner.sh"