[build]
target = "aarch64-linux-android"

[target.aarch64-linux-android]
ar = "android-ndk/arm64/bin/aarch64-linux-android-clang"
linker = "android-ndk/arm64/bin/aarch64-linux-android-clang"
runner = "runners/adb_runner.sh"

[env]
CC_aarch64_linux_android = { value = "android-ndk/arm64/bin/aarch64-linux-android-clang", relative = true }
AR_aarch64_linux_android = { value = "android-ndk/arm64/bin/llvm-ar", relative = true }
RUST_TEST_THREADS = "1"
