on: [push, pull_request]
name: Rust check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup build
        run: sudo apt-get install gcc-aarch64-linux-gnu && rustup component add llvm-tools && rustup target add aarch64-unknown-linux-gnu
      - name: Clippy
        run: cargo clippy --all-targets --all-features --target aarch64-unknown-linux-gnu
      - name: Run Format
        run: cargo fmt --all -- --check
